### ISSUE TITLE
Adjusting dependencies to JupySQL

### ISSUE THREAD

**Issue by idomic** [jtkiley/carma_python#2] opened 2023-04-07 20:05 UTC
I think it'll be beneficial for you to use [Jupysql](https://github.com/ploomber/jupysql) in your repo as we've added support in many interactive features on top of `ipython-sql`. There's backward compatibility so it's just changing the dependency.

**Comment by jtkiley** [comment] 2023-04-11 14:56
Duplicate of #1.

**Comment by idomic** [comment] 2023-04-11 15:17
Sorry for this!

**Comment by jtkiley** [comment] 2023-05-28 16:17
@idomic Thanks for the heads-up about `ipython-sql` pointing to `jupysql` for future work over on #1. It looks good on my end after adjusting the connection string syntax.

**Closed as completed** 2023-05-28 16:21 UTC
